prompt-proto-service:

  # -- Annotations for the prompt-proto-service pod
  podAnnotations:
    autoscaling.knative.dev/min-scale: "10"
    autoscaling.knative.dev/max-scale: "600"
    autoscaling.knative.dev/target-utilization-percentage: "60"
    autoscaling.knative.dev/target-burst-capacity: "-1"
    # Update this field if using latest or static image tag in dev
    revision: "1"

  image:
    repository: ghcr.io/lsst-dm/prompt-proto-service
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  instrument:
    name: ""
    pipelines: ""
    skymap: ""
    calibRepo: ""

  s3:
    imageBucket: ""
    endpointUrl: ""
    auth_env: true
    disableBucketValidation: '0'

  imageNotifications:
    kafkaClusterAddress: ""
    topic: ""
    imageTimeout: '120'

  apdb:
    ip: ""
    db: lsst-devl
    user: rubin
    namespace: pp_apdb

  registry:
    ip: ""
    db: lsstdb1
    user: rubin

  knative:
    ephemeralStorageRequest: "20Gi"
    ephemeralStorageLimit: "20Gi"
    timeout: 900
    idleTimeout: 900
    responseStartTimeout: 900

  vaultSecretsPath: ""
