apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: cadc-tap
  labels:
    app: {{ template "cadc-tap.fullname" . }}
{{- include "cadc-tap.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/{{ .Values.config.vaultSecretName }}"
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: pull-secret
  labels:
    {{- include "cadc-tap.labels" . | nindent 4 }}
spec:
  path: "{{- .Values.global.vaultSecretsPath }}/pull-secret"
  type: kubernetes.io/dockerconfigjson
