apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "giftless.fullname" . }}
  labels:
    {{- include "giftless.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPath }}/giftless"
  type: "Opaque"
