orders:
  commission:
    - name: initcommission
      image: lsstsqre/inituserhome
      securityContext:
        runAsUser: 1000
        runAsNonRootUser: true
      volumeMounts:
        - mountPath: /homedirs
          name: homedirs
  volumes:
    - name: homedirs
      nfs:
        server: 192.41.122.94
        path: /jhome
