apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "consdb"
spec:
  podSelector:
    matchLabels:
      component: pq
      {{- include "consdb.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    # Allow inbound access from pods (in any namespace)
    - from:
        - namespaceSelector: {}
          podSelector: {}
      ports:
        - protocol: "TCP"
          port: 8080
