apiVersion: v1
kind: Service
metadata:
  name: "consdb-pq"
  labels:
    {{- include "consdb.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: 8080
      targetPort: "http"
      protocol: "TCP"
      name: "http"
  selector:
    component: pq
    {{- include "consdb.selectorLabels" . | nindent 4 }}
