cadc-tap:
  config:
    uwsDatabaseUrl: "postgresql://localhost:5432/ssotap"
    uwsDatabaseUsername: "ssotap"

  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-idfdev-sso"

  uws:
    enabled: false

  cloudsql:
    enabled: true
    instanceConnectionName: "science-platform-dev-7696:us-central1:science-platform-dev-e9e11de2"
    serviceAccount: "ssotap@science-platform-dev-7696.iam.gserviceaccount.com"
