cadc-tap:
  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-idfdev-sso"
  config:
    databaseUrl: "postgresql://ssotap-uws@localhost/ssotap-uws"
  cloudsql:
    enabled: true
    instanceConnectionName: "science-platform-dev-7696:us-central1:science-platform-dev-e9e11de2"
    serviceAccount: "ssotap-uws@science-platform-dev-7696.iam.gserviceaccount.com"
