name: "minikube"
fqdn: "minikube.lsst.codes"
vaultUrl: "http://192.168.2.10:8200"
vaultPathPrefix: "secret/phalanx/minikube"

# The primary constraint on enabling applications is the low available memory
# of a GitHub Actions runner, since minikube is used for smoke testing of new
# Helm configurations. minikube also doesn't have access to data, at least
# currently, which substantially limits the applications that can be
# meaningfully deployed.
applications:
  mobu: true
  postgres: true
  portal: true
  globalclock: true
