name: minikube
fqdn: minikube.lsst.codes
vaultUrl: "https://vault.lsst.codes"
vaultPathPrefix: secret/k8s_operator/minikube.lsst.codes

# The primary constraint on enabling applications is the low available memory
# of a GitHub Actions runner, since minikube is used for smoke testing of new
# Helm configurations.
applications:
  datalinker: true
  hips: true
  mobu: true
  postgres: true
  squareone: true
  tap: true
