name: "idfint"
fqdn: "data-int.lsst.cloud"
butlerRepositoryIndex: "s3://butler-us-central1-repo-locations/data-int-repos.yaml"
butlerServerRepositories:
  dp02: "https://data-int.lsst.cloud/api/butler/repo/dp02/butler.yaml"
gcp:
  projectId: "science-platform-int-dc5d"
  region: "us-central1"
  clusterName: "science-platform-int"
onepassword:
  connectUrl: "https://roundtable.lsst.cloud/1password"
  vaultTitle: "RSP data-int.lsst.cloud"
vaultPathPrefix: "secret/phalanx/idfint"

applications:
  butler: true
  datalinker: true
  filestore-backup: true
  hips: true
  linters: true
  mobu: true
  nublado: true
  plot-navigator: true
  portal: true
  postgres: true
  sasquatch: true
  siav2: true
  ssotap: true
  production-tools: true
  semaphore: true
  sherlock: true
  squareone: true
  strimzi: true
  tap: true
  telegraf: true
  telegraf-ds: true
  vo-cutouts: true
