name: "idfprod"
fqdn: "data.lsst.cloud"
butlerRepositoryIndex: "s3://butler-us-central1-repo-locations/data-repos.yaml"
butlerServerRepositories:
  dp01: "https://data.lsst.cloud/api/butler/repo/dp01/butler.yaml"
  dp02: "https://data.lsst.cloud/api/butler/repo/dp02/butler.yaml"
gcp:
  projectId: "science-platform-stable-6994"
  region: "us-central1"
  clusterName: "science-platform-stable"
onepassword:
  connectUrl: "https://roundtable.lsst.cloud/1password"
  vaultTitle: "RSP data.lsst.cloud"
vaultPathPrefix: "secret/phalanx/idfprod"

applications:
  butler: true
  datalinker: true
  filestore-backup: true
  hips: true
  mobu: true
  nublado: true
  portal: true
  semaphore: true
  sherlock: true
  siav2: true
  squareone: true
  ssotap: true
  tap: true
  telegraf: true
  telegraf-ds: true
  vo-cutouts: true
