# These four settings should be set in each environment values-*.yaml file.

# -- Butler repository index to use for this environment
# @default -- None, must be set
butlerRepositoryIndex: ""

# -- Name of the environment
# @default -- None, must be set
name: ""

# -- Fully-qualified domain name where the environment is running
# @default -- None, must be set
fqdn: ""

# -- UUID of the 1Password item in which to find Vault tokens
onepasswordUuid: "dg5afgiadsffeklfr6jykqymeu"

# -- URL of the repository for all applications
repoUrl: https://github.com/lsst-sqre/phalanx.git

# -- Revision of repository to use for all applications
targetRevision: "main"

# -- URL of Vault server for this environment
# @default -- None, must be set
vaultUrl: ""

# -- Prefix for Vault secrets for this environment
# @default -- None, must be set
vaultPathPrefix: ""

applications:
  # -- Enable the alert-stream-broker application
  alert-stream-broker: false

  # -- Enable the argo-workflows application
  argo-workflows: false

  # -- Enable the Argo CD application. This must be enabled for all
  # environments and is present here only because it makes parsing easier
  argocd: true

  # -- Enable the cachemachine application (required by nublado2)
  cachemachine: false

  # -- Enable the cert-manager application, required unless the environment
  # makes separate arrangements to inject a current TLS certificate
  cert-manager: true

  # -- Eanble the datalinker application
  datalinker: false

  # -- Enable the exposurelog application
  exposurelog: false

  # -- Enable the Gafaelfawr application. This is required by Phalanx since
  # most other applications use `GafaelfawrIngress`
  gafaelfawr: true

  # -- Enable the giftless application
  giftless: false

  # -- Enable the HiPS application
  hips: false

  # -- Enable the ingress-nginx application. This is required for all
  # environments, but is still configurable because currently USDF uses an
  # unsupported configuration with ingress-nginx deployed in a different
  # cluster.
  ingress-nginx: true

  # -- Enable the kubernetes-replicator application
  kubernetes-replicator: false

  # -- Enable the linters application
  linters: false

  # -- Enable the livetap application
  livetap: false

  # -- Enable the mobu application
  mobu: false

  # -- Enable the moneypenny application (required by nublado2)
  moneypenny: false

  # -- Enable the monitoring application
  monitoring: false

  # -- Enable the narrativelog application
  narrativelog: false

  # -- Enable the noteburst application (required by times-square)
  noteburst: false

  # -- Enable the nublado application (v3 of the Notebook Aspect)
  nublado: false

  # -- Enable the nublado2 application (v2 of the Notebook Aspect, now
  # deprecated). This should not be used for new environments.
  nublado2: false

  # -- Enable the onepassword-connect-dev application
  onepassword-connect-dev: false

  # -- Enable the ook application
  ook: false

  # -- Enable the obsloctap application
  obsloctap: false

  # -- Enable the plot-navigator application
  plot-navigator: false

  # -- Enable the portal application
  portal: false

  # -- Enable the in-cluster PostgreSQL server. Use of this server is
  # discouraged in favor of using infrastructure SQL, but will remain
  # supported for use cases such as minikube test deployments.
  postgres: false

  # -- Enable the rubintv application
  rubintv: false

  # -- Enable the sasquatch application
  sasquatch: false

  # -- Enable the ssotap application
  ssotap: false

  # -- Enable the production-tools application
  production-tools: false

  # -- Enable the prompt-proto-service-hsc application
  prompt-proto-service-hsc: false

  # -- Enable the prompt-proto-service-latiss application
  prompt-proto-service-latiss: false

  # -- Enable the prompt-proto-service-lsstcam application
  prompt-proto-service-lsstcam: false

  # -- Enable the prompt-proto-service-lsstcomcam application
  prompt-proto-service-lsstcomcam: false

  # -- Enable the semaphore application
  semaphore: false

  # -- Enable the sherlock application
  sherlock: false

  # -- Enable the sqlproxy-cross-project application
  sqlproxy-cross-project: false

  # -- Enable the squarebot application
  squarebot: false

  # -- Enable the squareone application
  squareone: false

  # -- Enable the strimzi application
  strimzi: false

  # -- Enable the strimzi-access-operator application
  strimzi-access-operator: false

  # -- Enable the tap application
  tap: false

  # -- Enable the telegraf application
  telegraf: false

  # -- Enable the telegraf-ds application
  telegraf-ds: false

  # -- Enable the times-square application
  times-square: false

  # -- Enable the vault-secrets-operator application. This is required for all
  # environments.
  vault-secrets-operator: true

  # -- Enable the vo-cutouts application
  vo-cutouts: false
