name: stvdev
vaultUrl: "https://vault.lsst.ac.uk"
environment: stvdev
fqdn: rspdev.ddns.net
vaultPathPrefix: secret/k8s_operator/stvdev

applications:
  cachemachine: true
  mobu: true
  moneypenny: true
  nublado2: true
  portal: true
  postgres: true
  squareone: true
  tap: true
