butlerRepositoryIndex: "s3://butler-us-central1-repo-locations/data-repos.yaml"
fqdn: data.lsst.cloud
name: idfprod
vaultUrl: "https://vault.lsst.codes"
vaultPathPrefix: secret/k8s_operator/data.lsst.cloud

applications:
  datalinker: true
  hips: true
  mobu: true
  nublado: true
  portal: true
  postgres: true
  semaphore: true
  sherlock: true
  squareone: true
  ssotap: true
  tap: true
  telegraf: true
  telegraf-ds: true
  vo-cutouts: true
