name: summit
fqdn: summit-lsp.lsst.codes
vaultUrl: "https://vault.lsst.codes"
vaultPathPrefix: secret/k8s_operator/summit-lsp.lsst.codes

applications:
  cachemachine: true
  exposurelog: true
  moneypenny: true
  narrativelog: true
  nublado: true
  nublado2: true
  portal: true
  postgres: true
  sasquatch: true
  squareone: true
  strimzi: true
  telegraf: true
  telegraf-ds: true
