name: roundtable-dev
fqdn: roundtable-dev.lsst.cloud
vaultUrl: "https://vault.lsst.codes"
vaultPathPrefix: secret/k8s_operator/roundtable-dev.lsst.cloud

applications:
  giftless: true
  kubernetes-replicator: true
  monitoring: true
  onepassword-connect-dev: true
  ook: true
  sasquatch: true
  squarebot: true
  squareone: true
  strimzi: true
  strimzi-access-operator: true
