prompt-proto-service:

  podAnnotations:
    # Update this field if using latest or static image tag in dev
    revision: "1"

  image:
    repository: ghcr.io/lsst-dm/prompt-proto-service
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: AuxTel20230524-w_2023_20

  instrument:
    calibRepo: s3://rubin-summit-users/

  s3:
    imageBucket: rubin-pp
    endpointUrl: https://s3dfrgw.slac.stanford.edu

  imageNotifications:
    kafkaClusterAddress: prompt-processing-kafka-bootstrap.kafka:9092
    topic: rubin-prompt-processing

  apdb:
    ip: usdf-prompt-processing-dev.slac.stanford.edu:5432

  registry:
    ip: usdf-butler.slac.stanford.edu:5432

  fullnameOverride: "prompt-proto-service-latiss"

  vaultSecretsPath: "secret/rubin/usdf-prompt-processing-dev/prompt-proto-service-latiss"
