prompt-proto-service:

  podAnnotations:
    # Update this field if using latest or static image tag in dev
    revision: "1"

  image:
    repository: ghcr.io/lsst-dm/prompt-service
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  instrument:
    pipelines: >-
      (survey="SURVEY")=[${PROMPT_PROCESSING_DIR}/pipelines/LATISS/ApPipe.yaml,
      ${PROMPT_PROCESSING_DIR}/pipelines/LATISS/Isr.yaml]
    calibRepo: s3://rubin:rubin-pp-users/central_repo/
    calibRepoPguser: latiss_prompt

  s3:
    imageBucket: rubin:rubin-pp
    endpointUrl: https://s3dfrgw.slac.stanford.edu
    disableBucketValidation: '1'

  imageNotifications:
    kafkaClusterAddress: prompt-processing-kafka-bootstrap.kafka:9092
    topic: rubin-prompt-processing

  apdb:
    url: postgresql://rubin@usdf-prompt-processing-dev.slac.stanford.edu/lsst-devl

  sasquatch:
    endpointUrl: https://usdf-rsp-dev.slac.stanford.edu/sasquatch-rest-proxy
    auth_env: false

  fullnameOverride: "prompt-proto-service-latiss"
