config:
  autostart:
    - name: "firefighter"
      count: 1
      users:
        - username: "bot-mobu-recommended"
          uidnumber: 74768
          gidnumber: 74768
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business:
        type: "NotebookRunner"
        options:
          repo_url: "https://github.com/lsst-sqre/system-test.git"
          repo_branch: "prod"
          max_executions: 1
          use_cachemachine: false
        restart: true
    - name: "tutorial"
      count: 1
      users:
        - username: "bot-mobu-tutorial"
          uidnumber: 74768
          gidnumber: 74768
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business:
        type: "NotebookRunner"
        options:
          repo_url: "https://github.com/rubin-dp0/tutorial-notebooks.git"
          repo_branch: "prod"
          max_executions: 1
          working_directory: "notebooks/tutorial-notebooks"
          use_cachemachine: false
        restart: true
