config:
  debug: true
  autostart:
    - name: "python"
      count: 1
      users:
      - username: "bot-mobu-recommended"
        uidnumber: 74768
        gidnumber: 74768
      scopes: ["exec:notebook"]
      business: "JupyterPythonLoop"
      options:
        jupyter:
          image_size: "Small"
      restart: true
