config:
  autostart:
    - name: "firefighter"
      count: 5
      user_spec:
        username_prefix: "bot-mobu-recommended"
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business:
        type: "NotebookRunner"
        options:
          repo_url: "https://github.com/lsst-sqre/system-test.git"
          repo_branch: "prod"
          max_executions: 1
          use_cachemachine: false
        restart: true
