config:
  autostart:
    - name: "tap"
      count: 1
      users:
        - username: "bot-mobu-tap"
          uidnumber: 74775
          gidnumber: 74775
      scopes: ["read:tap"]
      business:
        type: "TAPQueryRunner"
        restart: true
        options:
          sync: true
          query: "SELECT TOP 10 * FROM Filter"
