config:
  autostart:
    - name: "firefighter"
      count: 1
      users:
        - username: "bot-mobu-recommended"
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business: "NotebookRunner"
      options:
        repo_url: "https://github.com/lsst-sqre/system-test.git"
        repo_branch: "prod"
        max_executions: 1
      restart: true
