config:
  autostart:
    - name: "python"
      count: 1
      users:
        - username: "bot-mobu-recommended"
          uidnumber: 74768
          gidnumber: 74768
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business:
        type: "JupyterPythonLoop"
        restart: true
        options:
            code: "print(1+1, end="")"
            max_executions: 1
    - name: "tap"
      count: 1
      users:
        - username: "bot-mobu-tap"
          uidnumber: 74775
          gidnumber: 74775
      scopes: ["read:tap"]
      business:
        type: "TAPQueryRunner"
        restart: true
        options:
          tap_sync: true
          tap_query_set: "dp0.2"
    - name: "firefighter"
      count: 5
      user_spec:
        username_prefix: "bot-mobu-weekly"
        uid_start: 74768
        gid_start: 74768
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business:
        type: "NotebookRunner"
        options:
          repo_url: "https://github.com/lsst-sqre/system-test.git"
          repo_branch: "prod"
          max_executions: 1
        restart: true
