config:
  autostart:
    - name: "tap"
      count: 1
      users:
        - username: "bot-mobu03"
          uidnumber: 45694
          gidnumber: 1126
      scopes: ["read:tap"]
      business:
        type: "TAPQueryRunner"
        options:
          query_set: "tap_schema"
        restart: true
