{{- if (index .Values "applications" "kubernetes-replicator") -}}
apiVersion: v1
kind: Namespace
metadata:
  name: "kubernetes-replicator"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "kubernetes-replicator"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    namespace: "kubernetes-replicator"
    server: "https://kubernetes.default.svc"
  project: "default"
  source:
    path: "applications/kubernetes-replicator"
    repoURL: {{ .Values.repoUrl | quote }}
    targetRevision: {{ .Values.targetRevision | quote }}
    helm:
      parameters:
        - name: "global.host"
          value: {{ .Values.fqdn | quote }}
        - name: "global.baseUrl"
          value: "https://{{ .Values.fqdn }}"
        - name: "global.vaultSecretsPath"
          value: {{ .Values.vaultPathPrefix | quote }}
      valueFiles:
        - "values.yaml"
        - "values-{{ .Values.name }}.yaml"
{{- end -}}
