argo-cd:
  configs:
    params:
      server.basehref: "/argo-cd"
      server.rootpath: "/argo-cd"
      server.insecure: true
    cm:
      url: "https://rsp-test.lsst.ac.uk"
      admin.enabled: true
  server:
    ingress:
      hostname: "rsp-test.lsst.ac.uk"
      tls: false
