apiVersion: v1
kind: ConfigMap
metadata:
  name: "cm-service"
  labels:
    {{- include "cm-service.labels" . | nindent 4 }}
data:
  CM_SERVICE_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  CM_SERVICE_PATH_PREFIX: {{ .Values.config.pathPrefix | quote }}
  CM_SERVICE_PROFILE: {{ .Values.config.logProfile | quote }}
