controller:
  googleServiceAccount: "nublado-controller@science-platform-stable-6994.iam.gserviceaccount.com"
  slackAlerts: true
  config:
    images:
      source:
        type: "google"
        location: "us-central1"
        projectId: "rubin-shared-services-71ec"
        repository: "sciplat"
        image: "sciplat-lab"
      recommendedTag: "recommended"
      numReleases: 1
      numWeeklies: 2
      numDailies: 3
    lab:
      env:
        AUTO_REPO_SPECS: "https://github.com/lsst-sqre/system-test@prod,https://github.com/rubin-dp0/tutorial-notebooks@prod"
        AWS_SHARED_CREDENTIALS_FILE: "/opt/lsst/software/jupyterlab/secrets/aws-credentials.ini"
        PGPASSFILE: "/opt/lsst/software/jupyterlab/secrets/postgres-credentials.txt"
        GOOGLE_APPLICATION_CREDENTIALS: "/opt/lsst/software/jupyterlab/secrets/butler-gcs-idf-creds.json"
        DAF_BUTLER_REPOSITORY_INDEX: "s3://butler-us-central1-repo-locations/data-repos.yaml"
        S3_ENDPOINT_URL: "https://storage.googleapis.com"
        NO_ACTIVITY_TIMEOUT: "432000"
        CULL_KERNEL_IDLE_TIMEOUT: "432000"
        CULL_TERMINAL_INACTIVE_TIMEOUT: "432000"

      sizes:
        small:
          cpu: 1.0
          memory: 4Gi
        medium:
          cpu: 2.0
          memory: 8Gi
        large:
          cpu: 4.0
          memory: 16Gi
      initContainers:
        - name: "initdir"
          image: "ghcr.io/lsst-sqre/initdir:0.0.4"
          privileged: true
          volumes:
            - containerPath: "/home"
              mode: "rw"
              source:
                serverPath: "/share1/home"
                server: "10.13.105.122"
                type: "nfs"
      secrets:
        - secretName: "nublado-lab-secret"
          secretKey: "aws-credentials.ini"
        - secretName: "nublado-lab-secret"
          secretKey: "butler-gcs-idf-creds.json"
        - secretName: "nublado-lab-secret"
          secretKey: "butler-hmac-idf-creds.json"
        - secretName: "nublado-lab-secret"
          secretKey: "postgres-credentials.txt"
      volumes:
        - containerPath: "/home"
          mode: "rw"
          source:
            serverPath: "/share1/home"
            server: "10.13.105.122"
            type: "nfs"
        - containerPath: "/project"
          mode: "rw"
          source:
            serverPath: "/share1/project"
            server: "10.13.105.122"
            type: "nfs"
        - containerPath: "/scratch"
          mode: "rw"
          source:
            serverPath: "/share1/scratch"
            server: "10.13.105.122"
            type: "nfs"

jupyterhub:
  hub:
    config:
      ServerApp:
        shutdown_no_activity_timeout: 432000
    db:
      url: "postgresql://nublado3@postgres.postgres/nublado3"

  cull:
    enabled: true
    users: false
    removeNamedServers: false
    timeout: 432000
    every: 300
    maxAge: 2160000
