config:
  serviceAccount: "vo-cutouts@science-platform-dev-7696.iam.gserviceaccount.com"
  storageBucketUrl: "gs://rubin-cutouts-dev-us-central1-output/"

cloudsql:
  enabled: true
  instanceConnectionName: "science-platform-dev-7696:us-central1:science-platform-dev-e9e11de2"
