jupyterhub:
  cull:
    enabled: true
    users: false
    removeNamedServers: false
    timeout: 432000
    every: 300
    maxAge: 2160000
  ingress:
    hosts: ["base-lsp.lsst.codes"]
    annotations:
      nginx.ingress.kubernetes.io/auth-signin: "https://base-lsp.lsst.codes/login"
  singleuser:
    extraAnnotations:
      k8s.v1.cni.cncf.io/networks: "kube-system/dds"
  hub:
    baseUrl: "/n2"
    db:
      upgrade: true
      url: "postgresql://jovyan@postgresdb01.ls.lsst.org/jupyterhub"

config:
  base_url: "https://base-lsp.lsst.codes"
  butler_secret_path: "secret/k8s_operator/base-lsp.lsst.codes/butler-secret"
  pull_secret_path: "secret/k8s_operator/base-lsp.lsst.codes/pull-secret"
  lab_environment:
    AUTO_REPO_URLS: "https://github.com/lsst-sqre/system-test"
    AUTO_REPO_BRANCH: "prod"
    AUTO_REPO_SPECS: "https://github.com/lsst-sqre/system-test@prod"
    DAF_BUTLER_REPOSITORY_INDEX: "/project/data-repos.yaml"
    LSST_DDS_INTERFACE: net1
    LSST_DDS_PARTITION_PREFIX: base
    LSST_SITE: base
    PGPASSFILE: "/opt/lsst/software/jupyterlab/butler-secret/postgres-credentials.txt"
    PGUSER: "oods"
  volumes:
    - name: home
      nfs:
        path: /jhome
        server: nfs-jhome.ls.lsst.org
    - name: project
      nfs:
        path: /project
        server: nfs-project.ls.lsst.org
    - name: scratch
      nfs:
        path: /scratch
        server: nfs-scratch.ls.lsst.org
    - name: datasets
      nfs:
        path: /lsstdata
        server: nfs-lsstdata.ls.lsst.org
    - name: auxtel-butler
      nfs:
        path: /auxtel/repo/LATISS
        server: nfs-auxtel.ls.lsst.org
    - name: auxtel-oods
      nfs:
        path: /auxtel/lsstdata/BTS/auxtel
        server: nfs-auxtel.ls.lsst.org
        readOnly: true
    - name: obs-env
      nfs:
        path: /obs-env
        server: nfs-obsenv.ls.lsst.org
  volume_mounts:
    - name: home
      mountPath: /home
    - name: datasets
      mountPath: /datasets
    - name: project
      mountPath: /project
    - name: scratch
      mountPath: /scratch
    - name: auxtel-butler
      mountPath: /repo/LATISS
    - name: auxtel-oods
      mountPath: /data/lsstdata/BTS/auxtel
      readOnly: true
    - name: obs-env
      mountPath: /net/obs-env
