cadc-tap:
  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-idfprod-tap"

  config:
    gcsBucket: "async-results.lsst.codes"
    gcsBucketUrl: "https://cccephs3.in2p3.fr:8080"
    gcsBucketType: "S3"

    qserv:
      host: "ccqserv201.in2p3.fr:30040"
