cadc-tap:
  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-idfprod-tap"

  mockdb:
    enabled: true

  config:
    jvmMaxHeapSize: 4G

  resources:
    requests:
      cpu: 0
      memory: 0
    limits:
      cpu: 0
      memory: 0

  uws:
    resources:
      requests:
        cpu: 0
        memory: 0
      limits:
        cpu: 0
        memory: 0
