redis:
  persistence:
    enabled: false

config:
  databaseUrl: "postgresql://gafaelfawr@postgres.postgres/gafaelfawr"

  github:
    clientId: "564b7b92b6c40a7c2348"

  # Allow access by GitHub team.
  groupMapping:
    "exec:admin":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "exec:notebook":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "exec:internal-tools":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "exec:portal":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "exec:user":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "read:workspace":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "read:workspace/user":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "write:workspace/user":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "read:image":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "read:tap":
      - github:
          organization: "lsp-uk"
          team: "dev"

  initialAdmins:
    - "stvoutsin"
